name: Update data for display
on:
  push
  #schedule:
    #- cron:  '0 1 * * *'
  
#workflow_dispatch:
jobs:
  Deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@v2 # Set up R
        with: 
          r-version: '4.4.1'
      #- uses: r-lib/actions/setup-pandoc@v2 # Set up pandoc for RMD file

      - name: Update system OpenSSL and curl
        run: |
          brew update
          brew upgrade openssl curl
        shell: bash
          
      - name: Install packages
        run: |
          install.packages("sf")
          install.packages("tidyverse")
          install.packages("lubridate")
          install.packages("leaflet")
          install.packages("shinyWidgets")
          install.packages("rinat")
          install.packages("rebird")
          install.packages("DT")
          install.packages("downloader")
          install.packages("purrr")
        #install.packages("curl", repos = "https://cloud.r-project.org")
        #install.packages("rsconnect", repos = "https://cloud.r-project.org")
        shell: Rscript {0}

          
      - name: Run rmd to update info
        #env:
          #CURL_CA_BUNDLE: $(brew --prefix openssl)/cert.pem
        run: Rscript get_app_data.R
        #run: |
        #    source("get_app_data.R")
        #shell: Rscript {0} 
