name: Update data for display
on:
  #schedule:
  #  - cron:  '0 8 * * 1'
  push:
    
jobs:
  Deploy:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@v2 # Set up R
        with: 
          r-version: '4.0.5'
      - uses: r-lib/actions/setup-pandoc@v2 # Set up pandoc for RMD file
          
      - name: Install packages
        run: |
          brew install gdal
          R -e 'install.packages("sf")'
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("leaflet")'
          R -e 'install.packages("shinyWidgets")'
          R -e 'install.packages("rinat")'
          R -e 'install.packages("rebird")'
          R -e 'install.packages("DT")'
          R -e 'install.packages("downloader")'
          R -e 'install.packages("purrr")'
          R -e 'install.packages("rsconnect")'
          
      - name: Run rmd to update info
        run: |
            source("get_app_data.R")
        shell: Rscript {0} 
      
      - name: Commit files # Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "daily update of welcome center display" && git push)
