name: Update data for display
on:
  #schedule:
  #  - cron:  '0 8 * * 1'
  push:
    
jobs:
  deploy:
    name: Deploy to shinyapp.io

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2-branch
      - uses: r-lib/actions/setup-pandoc@v1
      - name: deploy
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          # account and application names
          appName: si_citizen_science_display
          accountName: schoodic-institute-data

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: 57B287A6E91E86DCCA29B542392AB8E2
          accountSecret: 6NZ1FD19vvDi6pKIQ+iMXgxiYyTsgOc2yEzTl4bC
