name: Update data for display
on:
  push
  #schedule:
    #- cron:  '0 1 * * *'
  
#workflow_dispatch:
jobs:
  Deploy:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{secrets.DEPLOY_SECRET}}
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@v2 # Set up R
        with: 
          r-version: '4.4.1'
      #- uses: r-lib/actions/setup-pandoc@v2 # Set up pandoc for RMD file

      - name: Update system OpenSSL and curl
        run: |
          brew update
          brew upgrade openssl curl
        shell: bash
          
      - name: Install packages
        run: |
          install.packages(c(
            "sf", "tidyverse", "lubridate", "leaflet",
            "shinyWidgets", "rinat", "rebird", "DT",
            "downloader", "purrr", "rsconnect", "curl"
          ), dependencies = TRUE)
        shell: Rscript {0}

          
      - name: Run rmd to update info
        run: Rscript get_app_data.R


      #- name: Set CURL_CA_BUNDLE
      #  run: echo "CURL_CA_BUNDLE=$(brew --prefix openssl)/etc/ssl/cert.pem" >> $GITHUB_ENV


      - name: shinyapp deploy
        env:
          CURL_CA_BUNDLE: ${{ env.CURL_CA_BUNDLE }}
        run: |
           rsconnect::setAccountInfo(name = 'schoodic-institute-data', token = '${{secrets.SHINYAPPS_TOKEN}}', secret = '${{secrets.SHINYAPPS_SECRET}}')
           rsconnect::deployApp(account = 'schoodic-institute-data', server = 'shinyapps.io', forceUpdate = TRUE)
        shell: Rscript {0}
